import Providers from './_providers/providers'
import type React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// layout.tsx
// └─ <Providers>          ← クライアント用 QueryClient を「用意する」だけ
//      └─ {children}      ← page.tsx の中身がここに入る

// page.tsx（サーバーコンポーネント）
// └─ <HydrationBoundary state={dehydrate(queryClient)}>
//      └─ <PokemonInfo />

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* ページレイアウトでサーバーとクライアントの境界を作る */}
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}